version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: pr_service
      POSTGRES_USER: pr_user
      POSTGRES_PASSWORD: pr_pass
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pr_user -d pr_service"]
      interval: 3s
      timeout: 2s
      retries: 10

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      HTTP_PORT: "8080"
      DB_DSN: "postgres://pr_user:pr_pass@db:5432/pr_service?sslmode=disable"
    ports:
      - "8080:8080"